/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/bookings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * @description Страница предстоящих встреч владельца календаря: единый список
         *     бронирований по всем типам событий.
         */
        get: operations["Bookings_listUpcoming"];
        put?: never;
        /**
         * @description Создать бронирование на выбранный гостем слот.
         *
         *     Правило занятости: на одно и то же время нельзя создать две записи,
         *     даже если это разные типы событий. Слот должен принадлежать окну
         *     записи по умолчанию — 14 дней от текущей даты.
         */
        post: operations["Bookings_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/event-types": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * @description Список типов событий (страница с видами брони для гостя: название,
         *     описание, длительность; используется также владельцем календаря).
         */
        get: operations["EventTypes_list"];
        put?: never;
        /**
         * @description Создать тип события. Доступно владельцу календаря: он сам задаёт id,
         *     название, описание и длительность в минутах.
         */
        post: operations["EventTypes_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/event-types/{eventTypeId}/slots": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * @description Список свободных слотов выбранного типа события на ближайшие 14 дней.
         *     Слоты, уже занятые бронированием любого типа события, в списке не
         *     возвращаются — на одно и то же время не может быть двух записей.
         */
        get: operations["Slots_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/event-types/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Получить один тип события по идентификатору. */
        get: operations["EventTypes_read"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * @description Свободный слот в календаре выбранного типа события.
         *     Слоты рассчитываются на 14 дней вперёд от текущей даты.
         */
        AvailableSlot: {
            /**
             * Format: date-time
             * @description Начало слота.
             */
            start: string;
            /**
             * Format: date-time
             * @description Конец слота: start + durationMinutes выбранного типа события.
             */
            end: string;
        };
        /** @description Бронирование, созданное гостем на свободный слот. */
        Booking: {
            id: string;
            /** @description Тип события, на который сделано бронирование. */
            eventTypeId: components["schemas"]["EventTypeId"];
            /**
             * Format: date-time
             * @description Начало забронированного слота.
             */
            start: string;
            /**
             * Format: date-time
             * @description Конец забронированного слота (вычисляется по длительности типа события).
             */
            end: string;
            /**
             * Format: date-time
             * @description Момент создания бронирования.
             */
            createdAt: string;
        };
        /** @description Тело запроса на создание бронирования гостем. */
        BookingCreate: {
            /** @description Идентификатор выбранного типа события. */
            eventTypeId: components["schemas"]["EventTypeId"];
            /**
             * Format: date-time
             * @description Начало выбранного гостем слота.
             */
            start: string;
        };
        /**
         * @description Бронирование вместе с данными о типе события — используется на странице
         *     владельца календаря со списком всех предстоящих встреч.
         */
        BookingWithEventType: {
            id: string;
            eventType: components["schemas"]["EventType"];
            /** Format: date-time */
            start: string;
            /** Format: date-time */
            end: string;
            /** Format: date-time */
            createdAt: string;
        };
        Error: {
            /** Format: int32 */
            code: number;
            message: string;
        };
        /**
         * @description Тип события, который создаёт владелец календаря.
         *     Гости используют его, чтобы понять, на что они записываются,
         *     и чтобы выбрать календарь для бронирования.
         */
        EventType: {
            /** @description Идентификатор задаётся владельцем календаря при создании. */
            id: components["schemas"]["EventTypeId"];
            /** @description Название типа события, например "Консультация". */
            name: string;
            /** @description Описание того, что будет происходить на встрече. */
            description: string;
            /**
             * Format: int32
             * @description Длительность встречи в минутах: от 5 минут до 8 часов.
             */
            durationMinutes: number;
        };
        /** @description Тело запроса на создание типа события владельцем календаря. */
        EventTypeCreate: {
            /** @description Идентификатор нового типа события, задаётся владельцем. */
            id: components["schemas"]["EventTypeId"];
            name: string;
            description: string;
            /** Format: int32 */
            durationMinutes: number;
        };
        /**
         * @description Идентификатор типа события — kebab-case из латиницы и цифр,
         *     например "consultation-30".
         *
         *     Формат ограничен, потому что идентификатор подставляется в пути
         *     `/event-types/{id}` и `/event-types/{id}/slots`, а также в адрес страницы
         *     записи в клиентском приложении — ссылка должна оставаться читаемой
         *     и не требовать процентного кодирования.
         */
        EventTypeId: string;
        /** @description Слот уже занят другим бронированием (любого типа события). */
        SlotAlreadyBookedError: {
            /** @enum {string} */
            code: "slot_already_booked";
            message: string;
        };
        /** @description Выбранный слот вне окна записи (14 дней от текущей даты) или не существует. */
        SlotNotAvailableError: {
            /** @enum {string} */
            code: "slot_not_available";
            message: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    Bookings_listUpcoming: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BookingWithEventType"][];
                };
            };
            /** @description An unexpected error response. */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    Bookings_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BookingCreate"];
            };
        };
        responses: {
            /** @description The request has succeeded and a new resource has been created as a result. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Booking"];
                };
            };
            /** @description Выбранный слот вне окна записи (14 дней от текущей даты) или не существует. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SlotNotAvailableError"];
                };
            };
            /** @description Слот уже занят другим бронированием (любого типа события). */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SlotAlreadyBookedError"];
                };
            };
            /** @description An unexpected error response. */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    EventTypes_list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EventType"][];
                };
            };
            /** @description An unexpected error response. */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    EventTypes_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EventTypeCreate"];
            };
        };
        responses: {
            /** @description The request has succeeded and a new resource has been created as a result. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EventType"];
                };
            };
            /** @description An unexpected error response. */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    Slots_list: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                eventTypeId: components["schemas"]["EventTypeId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AvailableSlot"][];
                };
            };
            /** @description An unexpected error response. */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    EventTypes_read: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["schemas"]["EventTypeId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EventType"];
                };
            };
            /** @description An unexpected error response. */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
}
